/*
Copyright 2020 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"

	"github.com/prometheus/client_golang/prometheus/promhttp"
	"sigs.k8s.io/aws-encryption-provider/pkg/cloud"
	"sigs.k8s.io/aws-encryption-provider/pkg/connection"
	"sigs.k8s.io/aws-encryption-provider/pkg/logging"
	"sigs.k8s.io/aws-encryption-provider/pkg/plugin"
	"sigs.k8s.io/aws-encryption-provider/pkg/server"
)

func main() {
	var (
		healthzPath = flag.String("healthz-path", "/healthz", "healthcheck path")
		healthzPort = flag.String("health-port", ":8080", "healthcheck port")
		addr        = flag.String("listen", "/var/run/kmsplugin/socket.sock", "GRPC listen address")
		key         = flag.String("key", "", "AWS KMS Key")
		region      = flag.String("region", "us-east-1", "AWS Region")
		kmsEndpoint = flag.String("kms-endpoint", "", "use this KMS endpoint instead of the one generated by AWS sdk")
		debug       = flag.Bool("debug", false, "Print debug level logs")
	)
	flag.Parse()

	logLevel := zapcore.InfoLevel
	if *debug {
		logLevel = zapcore.DebugLevel
	}

	l, err := logging.NewStandardLogger(logLevel)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to configure logging")
		os.Exit(1)
	}

	zap.ReplaceGlobals(l)

	c, err := cloud.New(*region, *kmsEndpoint)
	if err != nil {
		zap.L().Fatal("Failed to create new KMS service", zap.Error(err))
	}

	s := server.New()
	p := plugin.New(*key, c)

	p.Register(s.Server)

	conn, err := connection.New(*addr)
	if err != nil {
		zap.L().Fatal("Failed to create connection", zap.Error(err))
	}

	client := plugin.NewClient(conn)

	go func() {
		http.HandleFunc(*healthzPath, func(w http.ResponseWriter, r *http.Request) {
			res, err := plugin.Check(client)
			if err != nil {
				w.WriteHeader(http.StatusInternalServerError)
				fmt.Fprint(w, http.StatusText(http.StatusInternalServerError))
				zap.L().Error("Failed healthceck", zap.Error(err))
			} else {
				w.WriteHeader(http.StatusOK)
				fmt.Fprint(w, http.StatusText(http.StatusOK))
				zap.L().Info("Passed healthceck", zap.String("version", res))
			}
		})

		http.Handle("/metrics", promhttp.Handler())

		if err := http.ListenAndServe(*healthzPort, nil); err != nil {
			zap.L().Fatal("Failed to start healthcheck server", zap.Error(err))
		}
	}()

	go func() {
		if err := s.ListenAndServe(*addr); err != nil {
			zap.L().Fatal("Failed to start server", zap.Error(err))
		}
	}()

	zap.L().Info("Healthchecks server started", zap.String("port", *healthzPort))
	zap.L().Info("Plugin server started", zap.String("port", *addr))

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)

	signal := <-signals

	zap.L().Info("Received signal", zap.Stringer("signal", signal))
	zap.L().Info("Closing client connection")
	conn.Close()
	zap.L().Info("Shutting down server")
	s.GracefulStop()
	zap.L().Info("Exiting...")
	os.Exit(0)
}
